stages:
  - build

.build: &build
  stage: build
  before_script:
    - opam repo add katamaran https://github.com/katamaran-project/opam-repository.git
    - opam install -vy coq-katamaran
    - opam list
  script:
    - make Makefile.coq
    - make -j$(nproc) -f Makefile.coq pretty-timed
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - "**/*.glob"
      - "**/*.vo*"
      - "**/.*.aux"
      - ".*.cache"
      - "_build"

8.14.1_iris-3.6.0_equations-1.3:   {<<: *build, image: "ghcr.io/katamaran-project/coq:8.14.1_iris-3.6.0_equations-1.3"}
8.14.1_iris-3.5.0_equations-1.3:   {<<: *build, image: "ghcr.io/katamaran-project/coq:8.14.1_iris-3.5.0_equations-1.3"}
8.15.0_iris-3.6.0_equations-1.3:   {<<: *build, image: "ghcr.io/katamaran-project/coq:8.15.0_iris-3.6.0_equations-1.3"}
