version: 2.1

defaults: &defaults
  steps:
    - checkout
    - run:
        name: Build project
        no_output_timeout: 1200
        command: |
          eval $(opam env)
          opam repo add katamaran https://github.com/katamaran-project/opam-repository.git
          opam install coq-katamaran
          opam list
          make Makefile.coq
          make -j$(nproc) -f Makefile.coq pretty-timed
  resource_class: medium+

jobs:
  coq-8-12: {<<: *defaults, docker: [{image: "skeuchel/coq:8.12"}]}
  coq-8-13: {<<: *defaults, docker: [{image: "skeuchel/coq:8.13"}]}

workflows:
  version: 2
  build:
    jobs:
      - "coq-8-12"
      - "coq-8-13"
