version: 2.1

defaults: &defaults
  steps:
    - checkout
    - run:
        name: Build project
        no_output_timeout: 1200
        command: |
          eval $(opam env)
          opam repo add katamaran https://github.com/katamaran-project/opam-repository.git
          opam install -vyj2 coq-katamaran
          opam list
          make Makefile.coq
          make -j$(nproc) -f Makefile.coq pretty-timed
  resource_class: medium+

jobs:
  coq-8-14: {<<: *defaults, docker: [{image: "ghcr.io/katamaran-project/coq:8.14.1_iris-3.6.0_equations-1.3"}]}
  coq-8-15: {<<: *defaults, docker: [{image: "ghcr.io/katamaran-project/coq:8.15.0_iris-3.6.0_equations-1.3"}]}

workflows:
  version: 2
  build:
    jobs:
      - "coq-8-14"
      - "coq-8-15"
